[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skatai-v2"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
data = ["pyarrow==18.1.0"]
training = ["numpy==1.26.4", "torch==2.1.2"]

[tool.pytest.ini_options]
testpaths = ["tests"]
